// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: UI_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen2;
extern lv_obj_t * uic_Label_Xmas_Counter;
extern lv_obj_t * uic_Label1;
extern lv_obj_t * uic_Label2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

